version: "3.9"

services:
  app:
    build:
      dockerfile: ./Dockerfile
    command:
      - "gunicorn"
      - "mysite.wsgi:application"
      - "--bind"
      - "0.0.0.0:8000"
#      - "python"
#      - "manage.py"
#      - "runserver"
#      - "0.0.0.0:8080"
    ports:
      - "8000:8000"
    restart: always
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "200k"
#      driver: loki
#      options:
#        loki-url: http://host.docker.internal:3100/loki/api/v1/push # куда передавать логи
##        loki-url: http://lokalhost:3100/loki/api/v1/push
      volumes:
        - ./mysite/database:/app/database
#      enviroment:
#        DJANGO_LOGLEVEL: WARNING
      env_file:
        - .env  # файл для хранения переменных окружения
#  grafana:
#    image: grafana/grafana:9.2.15  # образ с хаба
#    environment:
#      - GF_AUTH_ANONYMOUS_ENABLED=true # для захода в графану без авторизации
#      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
#    ports:
#      - "3000:3000"
#
#  loki:
#    image: grafana/loki:2.8.0
#    ports:
#      - "3100:3100"

