# Generated by Django 4.2.9 on 2024-01-21 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0006_order_products'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name', 'price'], 'verbose_name_plural': 'products'},
        ),
        migrations.AlterModelTable(
            name='product',
            table='tech_products',
        ),
    ]
